name: Deploy to FTP server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Node.js 18を使用
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Build and Export
        run: |
          npm ci
          npm run build

      - name: Deploy pro to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }} 
          local-dir: ./dist/